name: fidooo_challenge
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.1
  go_router: ^12.0.1
  mobx: ^2.2.1
  mobx_codegen: ^2.4.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
